version: "3.5"

services:
  postgres:
    image: postgres:11.4
    container_name: flowbuild_db
    restart: always
    environment:
      POSTGRES_USER: flowbuild
      POSTGRES_PASSWORD: flowbuild
      POSTGRES_DB: flowbuild
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080